#vich_uploader:
#    db_driver: orm

#    mappings:
#        media_object:
#            uri_prefix: '%env(PHOTO_URI_PREFIX)%' 
#            upload_destination: '%env(BASE_PHOTO_DIR)%' 
#            namer: vich_uploader.mappings.media_object.namer
#            directory_namer: vich_uploader.mappings.media_object.directory_namer


# Source non modifié
# Apparemment tout est placé dans le dossier BASE_PHOTO_DIR dans la source
# Voir ma config ci-dessous : il est possible de personnaliser le dossier d'upload directement
# dans la classe de l'entité (Photo par exemple)
# Voir par exemple la classe PdfFile (/src/entity) que j'ajoute (commit plus loin)
# Note : cela nécessite également l'ajout d'une variable "vichUploaderDirectoryName" dans la classe

vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'vichUploaderDirectoryName', transliterate: false}
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            